version: '3.8'

services:
  bank-api:
    image: bank-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
